name: Atualizar dados FUTZONE

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Buscar dados
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: |
          mkdir -p data

          echo "A testar API-Football..."

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/fixtures?league=94&season=2026" \
            -o data/primeira-liga.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/fixtures?league=39&season=2026" \
            -o data/premier-league.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/fixtures?league=140&season=2026" \
            -o data/la-liga.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/fixtures?league=135&season=2026" \
            -o data/serie-a.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/fixtures?league=78&season=2026" \
            -o data/bundesliga.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/standings?league=94&season=2026" \
            -o data/classificacao.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/standings?league=39&season=2026" \
            -o data/premier-league-classificacao.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/standings?league=140&season=2026" \
            -o data/la-liga-classificacao.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/standings?league=135&season=2026" \
            -o data/serie-a-classificacao.json

          sleep 5

          curl -sS \
            -H "x-apisports-key: $API_KEY" \
            "https://v3.football.api-sports.io/standings?league=78&season=2026" \
            -o data/bundesliga-classificacao.json

      - name: Guardar dados
        run: |
          git config user.name "FUTZONE"
          git config user.email "futzone@users.noreply.github.com"

          git add data/

          git diff --cached --quiet || git commit -m "Atualizar dados FUTZONE"

          git push
